services:
    dev:
        build:
            context: .
            dockerfile: Containerfile
            args:
                NEOVIM_CONFIG_URL: 'https://github.com/Vakarva/nvim'
                NODE_VERSION: 'lts/*'
                PYTHON_VERSIONS: ''
        image: dev-env
        network_mode: host
        container_name: dev-container
        environment:
            - TERM=xterm-ghostty
            - TZ=America/Los_Angeles
        stdin_open: true
        tty: true
        command: sleep infinity
        working_dir: /workspace
        volumes:
            - workspace:/workspace
            - $HOME/.ssh:/root/.ssh:ro,Z
            - $HOME/.gitconfig:/root/.gitconfig:ro,Z

volumes:
    workspace:
        external: true
